### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by Blitz-GM** [linrock/blitz-tactics#3]
Recently I've been unable to log in on y account (Nico) it is on the scoreboard and It would mean a  lot of trouble to restart. I just get this error message -We're sorry, but something went wrong.
If you are the application owner check the logs for more information.-when I tap on the sign up botton.
Please Help!

**Comment by linrock** [comment]
sorry about that and thanks for reporting! this problem should be fixed now

**Comment by Blitz-GM** [comment]
Thanks
