### ISSUE TITLE
Front Page Bug

### ISSUE THREAD

**Issue by Samuel-Pedraza** [linrock/blitz-tactics#35]
Hi there,

Heroku is stating the following whenever I visit the homepage:
![We're sorry, but something went wrong  500 ](https://user-images.githubusercontent.com/11684966/89107259-955b1500-d3e4-11ea-80c0-9b504fb50e4f.png)

Not sure if other people have this issue too? The rest of the website works fine.

**Comment by linrock** [comment]
Thanks for letting me know! The problem was the speedrun/countdown puzzles ran out. Fixed now.

**Comment by ajayasub** [comment]
the same problem has arrived to me on repetition level 3.
![image](https://user-images.githubusercontent.com/69710188/125885593-80b4f040-3723-444d-938c-a9e9fb9a6d0c.png)

**Comment by linrock** [comment]
@ajayasub thanks for the report! should be fixed now
