### ISSUE TITLE
Promotion: the colour of the pieces should match your colour

### ISSUE THREAD

**Issue by mmavova** [linrock/blitz-tactics#43]
When you promote a pawn, a window selection appears (Queen-Rook-Bishop-Knight). 
It always shows *white* pieces. The colour of the pieces should match the colour of the side you are playing for.

**Comment by linrock** [comment]
thanks for reporting! this is now fixed in https://github.com/linrock/blitz-tactics/commit/51cf4b. some links for testing:
- https://blitztactics.com/p/30000 - white to promote
- https://blitztactics.com/p/73553 - black to promote
