### ISSUE TITLE
Promotion on phone

### ISSUE THREAD

**Issue by yanganyi** [linrock/blitz-tactics#45]
When I accidentally promoted a pawn, I cannot cancel the promotion and I am forced to promote, breaking my streak, and in the mode “three” it results in a very fatal mistake. Hope you can fix this soon, thanks!

**Comment by linrock** [comment]
thanks for reporting! this should be fixed now in https://github.com/linrock/blitz-tactics/commit/383e6b. on your phone, you can now tap on the background area to back out of the piece promotion instead of being forced to promote.
