### ISSUE TITLE
Not Promoting Breaks Board

### ISSUE THREAD

**Issue by corn-syrup** [linrock/blitz-tactics#48]
Not promoting (by clicking outside of the promotion popup) breaks the board, in that your pieces can no longer be moved.

https://blitztactics.com/p/75198
1. Re6+ Kh7 2. Rxd6 Rxd6 3. c7 Rxd5 4. c8 ...

**Comment by linrock** [comment]
thanks for reporting! fixed in https://github.com/linrock/blitz-tactics/commit/4b90d52fb7fbc984d7eaedf143766bae3b5b40ba
